version: '3.8'

services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8800
    volumes:
      - .:/app
    ports:
      - "8800:8800"
    environment:
      - API_BASE_URL=https://labs.freesound.org/sens/api
