# Generated by Django 5.1.2 on 2024-10-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='uuid',
            field=models.CharField(default='werwr', max_length=100),
            preserve_default=False,
        ),
    ]
