# Generated by Django 5.1.2 on 2024-11-06 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensordata_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='sensor_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
